// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT IT DIRECTLY
import {
  BackfillWalletAggregatesDocument,
  BackfillWalletAggregatesMutationVariables,
  CreateApiTokensDocument,
  CreateApiTokensMutationVariables,
  CreateWebhooksDocument,
  CreateWebhooksMutationVariables,
  DeleteApiTokenDocument,
  DeleteApiTokenMutationVariables,
  DeleteWebhooksDocument,
  DeleteWebhooksMutationVariables,
  RefreshBalancesDocument,
  RefreshBalancesMutationVariables,
} from "./generated/graphql";
import { Codex } from "./index";

export class Mutation {
  constructor(private sdk: Codex) {}
  backfillWalletAggregates = async (
    vars: BackfillWalletAggregatesMutationVariables,
  ) => this.sdk.mutation(BackfillWalletAggregatesDocument, vars);
  createApiTokens = async (vars: CreateApiTokensMutationVariables) =>
    this.sdk.mutation(CreateApiTokensDocument, vars);
  createWebhooks = async (vars: CreateWebhooksMutationVariables) =>
    this.sdk.mutation(CreateWebhooksDocument, vars);
  deleteApiToken = async (vars: DeleteApiTokenMutationVariables) =>
    this.sdk.mutation(DeleteApiTokenDocument, vars);
  deleteWebhooks = async (vars: DeleteWebhooksMutationVariables) =>
    this.sdk.mutation(DeleteWebhooksDocument, vars);
  refreshBalances = async (vars: RefreshBalancesMutationVariables) =>
    this.sdk.mutation(RefreshBalancesDocument, vars);
}
