// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT IT DIRECTLY
import {
  ApiTokenDocument,
  ApiTokenQueryVariables,
  ApiTokensDocument,
  ApiTokensQueryVariables,
  BalancesDocument,
  BalancesQueryVariables,
  BlocksDocument,
  BlocksQueryVariables,
  ChartUrlsDocument,
  ChartUrlsQueryVariables,
  DetailedPredictionEventStatsDocument,
  DetailedPredictionEventStatsQueryVariables,
  DetailedPredictionMarketStatsDocument,
  DetailedPredictionMarketStatsQueryVariables,
  DetailedPredictionTraderStatsDocument,
  DetailedPredictionTraderStatsQueryVariables,
  DetailedWalletStatsDocument,
  DetailedWalletStatsQueryVariables,
  FilterExchangesDocument,
  FilterExchangesQueryVariables,
  FilterPairsDocument,
  FilterPairsQueryVariables,
  FilterPredictionEventsDocument,
  FilterPredictionEventsQueryVariables,
  FilterPredictionMarketsDocument,
  FilterPredictionMarketsQueryVariables,
  FilterPredictionTraderMarketsDocument,
  FilterPredictionTraderMarketsQueryVariables,
  FilterPredictionTradersDocument,
  FilterPredictionTradersQueryVariables,
  FilterTokensDocument,
  FilterTokensQueryVariables,
  FilterTokenWalletsDocument,
  FilterTokenWalletsQueryVariables,
  FilterWalletsDocument,
  FilterWalletsQueryVariables,
  GetBarsDocument,
  GetBarsQueryVariables,
  GetCommunityNotesDocument,
  GetCommunityNotesQueryVariables,
  GetDetailedPairsStatsDocument,
  GetDetailedPairsStatsQueryVariables,
  GetDetailedPairStatsDocument,
  GetDetailedPairStatsQueryVariables,
  GetDetailedTokenStatsDocument,
  GetDetailedTokenStatsQueryVariables,
  GetEventLabelsDocument,
  GetEventLabelsQueryVariables,
  GetExchangesDocument,
  GetExchangesQueryVariables,
  GetNetworkConfigsDocument,
  GetNetworkConfigsQueryVariables,
  GetNetworksDocument,
  GetNetworksQueryVariables,
  GetNetworkStatsDocument,
  GetNetworkStatsQueryVariables,
  GetNetworkStatusDocument,
  GetNetworkStatusQueryVariables,
  GetSymbolDocument,
  GetSymbolQueryVariables,
  GetTokenBarsDocument,
  GetTokenBarsQueryVariables,
  GetTokenEventsDocument,
  GetTokenEventsForMakerDocument,
  GetTokenEventsForMakerQueryVariables,
  GetTokenEventsQueryVariables,
  GetTokenPricesDocument,
  GetTokenPricesQueryVariables,
  GetWebhooksDocument,
  GetWebhooksQueryVariables,
  HoldersDocument,
  HoldersQueryVariables,
  LiquidityLocksDocument,
  LiquidityLocksQueryVariables,
  LiquidityMetadataByTokenDocument,
  LiquidityMetadataByTokenQueryVariables,
  LiquidityMetadataDocument,
  LiquidityMetadataQueryVariables,
  ListPairsForTokenDocument,
  ListPairsForTokenQueryVariables,
  ListPairsWithMetadataForTokenDocument,
  ListPairsWithMetadataForTokenQueryVariables,
  PairMetadataDocument,
  PairMetadataQueryVariables,
  PredictionCategoriesDocument,
  PredictionCategoriesQueryVariables,
  PredictionEventBarsDocument,
  PredictionEventBarsQueryVariables,
  PredictionEventTopMarketsBarsDocument,
  PredictionEventTopMarketsBarsQueryVariables,
  PredictionMarketBarsDocument,
  PredictionMarketBarsQueryVariables,
  PredictionMarketsDocument,
  PredictionMarketsQueryVariables,
  PredictionTokenHoldersDocument,
  PredictionTokenHoldersQueryVariables,
  PredictionTraderBarsDocument,
  PredictionTraderBarsQueryVariables,
  PredictionTraderMarketsStatsDocument,
  PredictionTraderMarketsStatsQueryVariables,
  PredictionTradersDocument,
  PredictionTradersQueryVariables,
  PredictionTradesDocument,
  PredictionTradesQueryVariables,
  TokenDocument,
  TokenLifecycleEventsDocument,
  TokenLifecycleEventsQueryVariables,
  TokenQueryVariables,
  TokensDocument,
  TokenSparklinesDocument,
  TokenSparklinesQueryVariables,
  TokensQueryVariables,
  TokenTopTradersDocument,
  TokenTopTradersQueryVariables,
  Top10HoldersPercentDocument,
  Top10HoldersPercentQueryVariables,
  WalletAggregateBackfillStateDocument,
  WalletAggregateBackfillStateQueryVariables,
  WalletChartDocument,
  WalletChartQueryVariables,
} from "./generated/graphql";
import { Codex } from "./index";

export class Query {
  constructor(private sdk: Codex) {}
  apiToken = async (vars: ApiTokenQueryVariables) =>
    this.sdk.query(ApiTokenDocument, vars);
  apiTokens = async (vars: ApiTokensQueryVariables) =>
    this.sdk.query(ApiTokensDocument, vars);
  balances = async (vars: BalancesQueryVariables) =>
    this.sdk.query(BalancesDocument, vars);
  blocks = async (vars: BlocksQueryVariables) =>
    this.sdk.query(BlocksDocument, vars);
  chartUrls = async (vars: ChartUrlsQueryVariables) =>
    this.sdk.query(ChartUrlsDocument, vars);
  detailedPredictionEventStats = async (
    vars: DetailedPredictionEventStatsQueryVariables,
  ) => this.sdk.query(DetailedPredictionEventStatsDocument, vars);
  detailedPredictionMarketStats = async (
    vars: DetailedPredictionMarketStatsQueryVariables,
  ) => this.sdk.query(DetailedPredictionMarketStatsDocument, vars);
  detailedPredictionTraderStats = async (
    vars: DetailedPredictionTraderStatsQueryVariables,
  ) => this.sdk.query(DetailedPredictionTraderStatsDocument, vars);
  detailedWalletStats = async (vars: DetailedWalletStatsQueryVariables) =>
    this.sdk.query(DetailedWalletStatsDocument, vars);
  filterExchanges = async (vars: FilterExchangesQueryVariables) =>
    this.sdk.query(FilterExchangesDocument, vars);
  filterPairs = async (vars: FilterPairsQueryVariables) =>
    this.sdk.query(FilterPairsDocument, vars);
  filterPredictionEvents = async (vars: FilterPredictionEventsQueryVariables) =>
    this.sdk.query(FilterPredictionEventsDocument, vars);
  filterPredictionMarkets = async (
    vars: FilterPredictionMarketsQueryVariables,
  ) => this.sdk.query(FilterPredictionMarketsDocument, vars);
  filterPredictionTraderMarkets = async (
    vars: FilterPredictionTraderMarketsQueryVariables,
  ) => this.sdk.query(FilterPredictionTraderMarketsDocument, vars);
  filterPredictionTraders = async (
    vars: FilterPredictionTradersQueryVariables,
  ) => this.sdk.query(FilterPredictionTradersDocument, vars);
  filterTokenWallets = async (vars: FilterTokenWalletsQueryVariables) =>
    this.sdk.query(FilterTokenWalletsDocument, vars);
  filterTokens = async (vars: FilterTokensQueryVariables) =>
    this.sdk.query(FilterTokensDocument, vars);
  filterWallets = async (vars: FilterWalletsQueryVariables) =>
    this.sdk.query(FilterWalletsDocument, vars);
  getBars = async (vars: GetBarsQueryVariables) =>
    this.sdk.query(GetBarsDocument, vars);
  getCommunityNotes = async (vars: GetCommunityNotesQueryVariables) =>
    this.sdk.query(GetCommunityNotesDocument, vars);
  getDetailedPairStats = async (vars: GetDetailedPairStatsQueryVariables) =>
    this.sdk.query(GetDetailedPairStatsDocument, vars);
  getDetailedPairsStats = async (vars: GetDetailedPairsStatsQueryVariables) =>
    this.sdk.query(GetDetailedPairsStatsDocument, vars);
  getDetailedTokenStats = async (vars: GetDetailedTokenStatsQueryVariables) =>
    this.sdk.query(GetDetailedTokenStatsDocument, vars);
  getEventLabels = async (vars: GetEventLabelsQueryVariables) =>
    this.sdk.query(GetEventLabelsDocument, vars);
  getExchanges = async (vars: GetExchangesQueryVariables) =>
    this.sdk.query(GetExchangesDocument, vars);
  getNetworkConfigs = async (vars: GetNetworkConfigsQueryVariables) =>
    this.sdk.query(GetNetworkConfigsDocument, vars);
  getNetworkStats = async (vars: GetNetworkStatsQueryVariables) =>
    this.sdk.query(GetNetworkStatsDocument, vars);
  getNetworkStatus = async (vars: GetNetworkStatusQueryVariables) =>
    this.sdk.query(GetNetworkStatusDocument, vars);
  getNetworks = async (vars: GetNetworksQueryVariables) =>
    this.sdk.query(GetNetworksDocument, vars);
  getSymbol = async (vars: GetSymbolQueryVariables) =>
    this.sdk.query(GetSymbolDocument, vars);
  getTokenBars = async (vars: GetTokenBarsQueryVariables) =>
    this.sdk.query(GetTokenBarsDocument, vars);
  getTokenEvents = async (vars: GetTokenEventsQueryVariables) =>
    this.sdk.query(GetTokenEventsDocument, vars);
  getTokenEventsForMaker = async (vars: GetTokenEventsForMakerQueryVariables) =>
    this.sdk.query(GetTokenEventsForMakerDocument, vars);
  getTokenPrices = async (vars: GetTokenPricesQueryVariables) =>
    this.sdk.query(GetTokenPricesDocument, vars);
  getWebhooks = async (vars: GetWebhooksQueryVariables) =>
    this.sdk.query(GetWebhooksDocument, vars);
  holders = async (vars: HoldersQueryVariables) =>
    this.sdk.query(HoldersDocument, vars);
  liquidityLocks = async (vars: LiquidityLocksQueryVariables) =>
    this.sdk.query(LiquidityLocksDocument, vars);
  liquidityMetadata = async (vars: LiquidityMetadataQueryVariables) =>
    this.sdk.query(LiquidityMetadataDocument, vars);
  liquidityMetadataByToken = async (
    vars: LiquidityMetadataByTokenQueryVariables,
  ) => this.sdk.query(LiquidityMetadataByTokenDocument, vars);
  listPairsForToken = async (vars: ListPairsForTokenQueryVariables) =>
    this.sdk.query(ListPairsForTokenDocument, vars);
  listPairsWithMetadataForToken = async (
    vars: ListPairsWithMetadataForTokenQueryVariables,
  ) => this.sdk.query(ListPairsWithMetadataForTokenDocument, vars);
  pairMetadata = async (vars: PairMetadataQueryVariables) =>
    this.sdk.query(PairMetadataDocument, vars);
  predictionCategories = async (vars: PredictionCategoriesQueryVariables) =>
    this.sdk.query(PredictionCategoriesDocument, vars);
  predictionEventBars = async (vars: PredictionEventBarsQueryVariables) =>
    this.sdk.query(PredictionEventBarsDocument, vars);
  predictionEventTopMarketsBars = async (
    vars: PredictionEventTopMarketsBarsQueryVariables,
  ) => this.sdk.query(PredictionEventTopMarketsBarsDocument, vars);
  predictionMarketBars = async (vars: PredictionMarketBarsQueryVariables) =>
    this.sdk.query(PredictionMarketBarsDocument, vars);
  predictionMarkets = async (vars: PredictionMarketsQueryVariables) =>
    this.sdk.query(PredictionMarketsDocument, vars);
  predictionTokenHolders = async (vars: PredictionTokenHoldersQueryVariables) =>
    this.sdk.query(PredictionTokenHoldersDocument, vars);
  predictionTraderBars = async (vars: PredictionTraderBarsQueryVariables) =>
    this.sdk.query(PredictionTraderBarsDocument, vars);
  predictionTraderMarketsStats = async (
    vars: PredictionTraderMarketsStatsQueryVariables,
  ) => this.sdk.query(PredictionTraderMarketsStatsDocument, vars);
  predictionTraders = async (vars: PredictionTradersQueryVariables) =>
    this.sdk.query(PredictionTradersDocument, vars);
  predictionTrades = async (vars: PredictionTradesQueryVariables) =>
    this.sdk.query(PredictionTradesDocument, vars);
  token = async (vars: TokenQueryVariables) =>
    this.sdk.query(TokenDocument, vars);
  tokenLifecycleEvents = async (vars: TokenLifecycleEventsQueryVariables) =>
    this.sdk.query(TokenLifecycleEventsDocument, vars);
  tokenSparklines = async (vars: TokenSparklinesQueryVariables) =>
    this.sdk.query(TokenSparklinesDocument, vars);
  tokenTopTraders = async (vars: TokenTopTradersQueryVariables) =>
    this.sdk.query(TokenTopTradersDocument, vars);
  tokens = async (vars: TokensQueryVariables) =>
    this.sdk.query(TokensDocument, vars);
  top10HoldersPercent = async (vars: Top10HoldersPercentQueryVariables) =>
    this.sdk.query(Top10HoldersPercentDocument, vars);
  walletAggregateBackfillState = async (
    vars: WalletAggregateBackfillStateQueryVariables,
  ) => this.sdk.query(WalletAggregateBackfillStateDocument, vars);
  walletChart = async (vars: WalletChartQueryVariables) =>
    this.sdk.query(WalletChartDocument, vars);
}
