name: Release package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i
      - run: bun run build
        env:
          CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
      - run: npm publish --access public
        env:
          NPM_TOKEN: ${{secrets.CODEX_SDK_NPM_TOKEN}}

      - name: Notify Discord
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{secrets.DISCORD_WEBHOOK_URL}}
          color: "2105893"
          avatar_url: "https://avatars.githubusercontent.com/u/175457154?s=200&v=4"
          content: "🚀 New SDK release is now available!"
